# -*- mode: python ; coding: utf-8 -*-
#
# LighthouseOCR — PyInstaller build spec
#
# Build command:
#   pyinstaller LighthouseOCR.spec
#
# Output:
#   dist/LighthouseOCR/          ← distribute the whole folder
#     LighthouseOCR.exe
#     _internal/                 ← bundled Python + libs (managed by PyInstaller)
#     Data structure/            ← master Excel files (editable by users)
#     env/                       ← copied by Deploy_Build.ps1 from project env/python_env
#     Setup_Moi_Truong.bat       ← copied by Deploy_Build.ps1 for client dependency repair
#     LighthouseOCR_Start.bat    ← generated by Deploy_Build.ps1 (runtime preflight launcher)
#
# Notes:
#   - PaddleOCR runs in a separate portable Python (env/) via subprocess.
#     OpenCV stays bundled because image preprocessing runs in the main app.
#   - Deploy_Build.ps1 handles runtime copy and startup bootstrap scripts.

block_cipher = None

a = Analysis(
    ['main_app_qt.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Master data files — placed alongside the exe so users can edit them
        ('Data structure', 'Data structure'),
        # Runtime assets
        ('app_style.qss', '.'),
        ('icon.ico', '.'),
        ('pipeline.yaml', '.'),
        ('excel_mapping_skill.md', '.'),
        ('ocr_calculation_skill.md', '.'),
        ('ocr_invoice_skill.md', '.'),
        ('ocr_text_structurer_skill.md', '.'),
        ('ocr_vision_handwritten_skill.md', '.'),
        # OCR subprocess script — called by module_paddle_ocr.py via portable Python
        ('ocr_runner.py', '.'),
    ],
    hiddenimports=[
        'PyQt5.sip',
        'openpyxl.cell._writer',
        'google.genai',
        'google.auth',
        'google.auth.transport.requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Exclude PaddleOCR stack — it runs in env/ subprocess, not in the main process.
    # Keep cv2 bundled: image_processor.py imports OpenCV in the main app process.
    excludes=['paddlepaddle', 'paddleocr', 'paddle', 'pytesseract'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,      # folder build (not onefile)
    name='LighthouseOCR',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,              # no terminal window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
    version_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='LighthouseOCR',       # → dist/LighthouseOCR/
)
